name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  COMPOSER_CACHE_DIR: /tmp/_composer_cache

jobs:
  unit-tests:
    name: Tests for php${{ matrix.php-versions }} ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4', '8.5']
        composer-command: ['install']
        include:
          - php-versions: '8.2'
            composer-command: 'update --prefer-lowest --prefer-dist --prefer-stable --no-interaction'
            name: prefer-lowest
    steps:
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
        coverage: xdebug
        ini-file: development
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Cache composer cache directory
      uses: actions/cache@v5
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: composer-cache
    - name: Unit tests
      run: |
        composer ${{ matrix.composer-command }}
        composer test
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
        coverage: xdebug
        tools: composer-require-checker:4
        ini-file: development
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Cache composer cache directory
      uses: actions/cache@v5
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: composer-cache
    - name: Unit tests
      run: |
        composer install
        result=0
        composer run cs || result=1
        composer run phpstan || result=1
        composer-require-checker || result=1
        exit $result
